# ~/.tmux.conf
# Summary
# prefix: C-a
# copy mode uses vim
# vim-style pane navigation and resizing
# vertical split: pre + -
# horizontal split: pre + |

########################
## Settings
########################

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Increase scrollback buffer
set -g history-limit 50000

########################
## Keybinds
########################

# Change prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Make Copy Mode use vim motions
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection            # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle         # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel  # Yank selection then quit copy mode.

# Better pane splitting (and keep current path)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
# Vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
